"""Pydantic schemas for Privacy-Preserved Model Inference and Customer Prediction Playground."""

from typing import Optional, Dict, Any, List
from pydantic import BaseModel, Field


class InferenceRequest(BaseModel):
    """Customer input parameters for disease risk prediction using the aggregated global model."""
    age: int = Field(..., ge=18, le=100, description="Patient age in years")
    gender: str = Field(..., pattern="^(Male|Female|Other)$")
    blood_pressure_sys: int = Field(..., ge=80, le=240, description="Systolic Blood Pressure (mmHg)")
    cholesterol: int = Field(..., ge=100, le=450, description="Serum Cholesterol (mg/dL)")
    glucose: int = Field(..., ge=50, le=350, description="Fasting Blood Glucose (mg/dL)")
    heart_rate: int = Field(..., ge=45, le=200, description="Resting Heart Rate (bpm)")
    smoking: bool = Field(False, description="Smoking status")


class InferenceResponse(BaseModel):
    """Prediction result generated by the Privacy-Preserving Global Federated Model."""
    prediction_risk_score: float = Field(..., description="Calculated cardiovascular/disease risk score (0.0 to 1.0)")
    risk_category: str = Field(..., description="'Low Risk', 'Moderate Risk', 'High Risk', 'Critical'")
    model_confidence: float = Field(..., description="Statistical confidence level (%)")
    global_model_version: str = Field(..., description="Active Global FL Model checkpoint identifier")
    global_accuracy: float = Field(..., description="Global accuracy of the model evaluated across all silos")
    privacy_guarantee: Dict[str, Any] = Field(
        ...,
        description="Differential privacy mathematical bounds and zero-knowledge verification details",
    )
    feature_contributions: Dict[str, float] = Field(
        ...,
        description="SHAP/Feature importance weights contributing to this prediction",
    )
